### ISSUE TITLE
Sous-Chefs Adoption

### ISSUE THREAD

**Issue by damacus** [damacus/packagecloud-cookbook#62]
Hey, 
it looks like this isn't maintained or used anymore by the current maintainers. Would you be open to migrating this over to [github.com/sous-chefs](https://github.com/sous-chefs/)? 

Thanks,
Dan

**Comment by nethsix** [comment]
Hello Dan,

We have a live chat on our website packagecloud.io and so far we've not received any request that something is broken.
We will fix any issues if a customer complains about this being broken.
Having said that, we would welcome the migration to sous-chefs if someone at sous-chefs help us to actively maintain it.
Is my assumption correct that someone from sous-chefs is strongly motivate to actively maintain it?
Please do contact us at support@packagecloud.io so that our support team can work with you.

Thank you very much.

**Comment by damacus** [comment]
will do when I'm back from leave 👍🏼
